### ISSUE TITLE
Operation ids for single resource paths have `*ById` suffix

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/microsoft-graph-devx-api#1317]
**Describe the bug**
In previous deployments of DevX API, operationIds for paths that modify/retrieve a single resource didn't have a `*ById` suffix. The current deployment of DevX API is adding a `*ById` suffix to  operationIds for single resource paths.

**To Reproduce**
1. Go to https://graphexplorerapi.azurewebsites.net/openapi?operationIds=applications.application.GetApplicationById&openApiVersion=2&graphVersion=v1.0&format=yaml&style=Plain
2. Inspect operationId:
  ``` yml
paths:
  '/applications/{application-id}':
    get:
      tags:
        - applications.application
      summary: Get application
      description: Get the properties and relationships of an application object.
      externalDocs:
        description: Find more info here
        url: https://docs.microsoft.com/graph/api/application-get?view=graph-rest-1.0
      operationId: applications.application.GetApplicationById
  ```

**Expected behavior**
Operations should not have `*ById` suffix:
``` yml
paths:
  '/applications/{application-id}':
    get:
      tags:
        - applications.application
      summary: Get application
      description: Get the properties and relationships of an application object.
      externalDocs:
        description: Find more info here
        url: https://docs.microsoft.com/graph/api/application-get?view=graph-rest-1.0
      operationId: applications.application_GetApplication
```

**Additional context**
This is a blocking issue for PowerShell since we use OperationIds to name our commands. The new suffix will cause a breaking change for PowerShell customers.
