### ISSUE TITLE
Test PowerShell integration with `Microsoft.OpenAPI.OData - v1.0.10-preview2` lib. 

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/microsoft-graph-devx-api#902]
The `Microsoft.OpenAPI.OData - v1.0.10-preview2` OData - OpenAPI conversion lib. is out! 
We need to test how this lib. integrates with PowerShell through DevX API via this test url: https://devxapitest.azurewebsites.net/ and bump up the lib version in this repo if successful.

**Comment by peombwa** [comment]
Here are the results from the first test with PowerShell SDK:
- All but three modules build after adding directives to fix circular references and broken commands
- DeviceManagement.Functions fails because we are using `content` instead of `schema` in the parameter object for `GET /deviceManagement/microsoft.graph.getRoleScopeTagsByIds(ids=@ids)` operation.
![image](https://user-images.githubusercontent.com/7061532/157346607-89f1375a-8349-4d60-ab6a-2cdf2052611f.png)
AutoREST.PowerShell doesn't support parameter objects with content. In this case, there is no need to no need for a content-type in a parameter. The ideal parameter object should be:
  ``` yml
  /deviceManagement/microsoft.graph.getRoleScopeTagsByIds(ids=@ids):
    get:
      tags:
        - deviceManagement.Functions
      summary: Invoke function getRoleScopeTagsByIds
      operationId: deviceManagement_getRoleScopeTagsByIds
      parameters:
        - name: ids
          in: query
          description: 'Usage: ids={ids}'
          required: true
          schema:
            type: array
            items:
              type: string
        ...
  ```
- Sites and Files timeout after 8+ hours due to the number of paths and schemas. We will need to review the paths individually and remove those that are invalid.
  - Sites
     - v1.0
          ``` powershell
			➜ hidi validate --openapi .\v1.0\Sites.yml
			Path Items: 715
			Operations: 1257
			Parameters: 7309
			Request Bodies: 388
			Responses: 1257
			Links: 1558
			Callbacks: 0
			Schemas: 11632
          ```
     - beta
          ``` powershell
			➜ hidi validate --openapi .\beta\Sites.yml
			Path Items: 507
			Operations: 880
			Parameters: 4521
			Request Bodies: 282
			Responses: 880
			Links: 1069
			Callbacks: 0
			Schemas: 9820
          ``` 
   - Files
     - v1.0
          ``` powershell
			➜ hidi validate --openapi .\v1.0\Files.yml
			Path Items: 546
			Operations: 1102
			Parameters: 4190
			Request Bodies: 384
			Responses: 1102
			Links: 979
			Callbacks: 0
			Schemas: 8018
          ```
     - beta
          ``` powershell
			➜ hidi validate --openapi .\beta\Files.yml
			Path Items: 733
			Operations: 1409
			Parameters: 5435
			Request Bodies: 489
			Responses: 1409
			Links: 1640
			Callbacks: 0
			Schemas: 11174
          ```
